# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    environment: playground

remote_write:
  - url: "http://prom2kafka:9201/write"
    queue_config:
      max_samples_per_send: 1000
      capacity: 5000
      max_shards: 30
     
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/rules/*.yml"
#  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'other_targets'
    file_sd_configs:
      - files:
        - "/etc/prometheus/targets/other_targets/*.json"
  - job_name: 'node exporter'
    file_sd_configs:
      - files:
        - "/etc/prometheus/targets/node_exporter_targets/*.json"
  - job_name: 'windows exporter'
    file_sd_configs:
      - files:
        - "/etc/prometheus/targets/windows_targets/*.json"
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'prom2kafka'
    static_configs:
      - targets: ['prom2kafka:9201']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:9099']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://pagertree.com
        - https://www.google.com
        - https://prometheus.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"
